# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install deps
      run: |
          go get github.com/gen2brain/raylib-go/raylib
          go get golang.org/x/exp/slices

    - name: Build
      run: |
        go build -v -o clickspeedtest
        go test -v
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
